### ISSUE TITLE
Documentation for ROSOMNeT

### ISSUE THREAD

**Issue by hakimkeb** [d3scomp/ROSOMNeT#1]
Hello,
First, thank you for your work, it's very interesting.
I am a student and I would also like to connect ROS and OMNeT however I do not know how to use your project.
Do you have an explanation file or READ ME?

**Comment by vladamatena** [comment]
Hi, this project is actually used here: https://github.com/d3scomp/deeco-adaptation-testbed . The testbed includes description on how to combine all the component including ROSOMNeT++ into a running system.
